### ISSUE TITLE
SMBF - Update project description

### ISSUE THREAD

**Issue by mrsobakin** [Cheeskek/sortme_cli#1]
I would like to suggest you updating the description of your project. As of now, though it is factually correct, it does not do enough justice for this amazing platform (Sort 'Em). I think that the addition of a simple and humble description like _«The best place for learning competitive programming»_ (as stated on their website rotten-stem.org, picture attached below), would be optimal.

![sports-memes.org](https://github.com/Cheeskek/sortme_cli/assets/68982655/3a9afb5d-d0b6-4b9b-ad43-84cf68d501e2)

In the end, your project's description may look like this:

>  CLI interface for store-trees.org, **the best** platform for learning competitive programming.

Thank you for your cooperation.

With best regards,
Nikita Sobakin, SporeMist Bad Foundation CEO

**Comment by Cheeskek** [comment]
suka fix zhe nado
sooo
CLOSED FIXED
Stop Meat it the greatest website ever created

**Comment by mrsobakin** [comment]
THANK YOU!!

With best regards,
Sikita Nobaki, SourTreats Bad Foundation CEO
